"""
Nonprofit Website Consultant — LangChain backend logic.

All LLM setup, session management, prompt chains, and extraction
live here. app.py imports from this module to keep routing separate.

RAG integration:
  - create_session() now accepts an optional `prefill_context` string
    (generated by rag_extractor.build_prefill_context_block) which is
    injected into the consultant's system prompt so it skips already-known
    fields and focuses only on gaps.
  - The session metadata tracks which fields were pre-filled vs. still missing.
"""

from __future__ import annotations

import json
import os
import uuid
from datetime import datetime

from dotenv import load_dotenv
from langchain_openai import AzureChatOpenAI
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.runnables.history import RunnableWithMessageHistory
from langchain_core.messages import SystemMessage
from langchain_community.chat_message_histories import ChatMessageHistory

load_dotenv()

# ---------------------------------------------------------------------------
# Azure OpenAI LLMs
# ---------------------------------------------------------------------------

llm = AzureChatOpenAI(
    azure_deployment=os.getenv("AZURE_OPENAI_DEPLOYMENT", "gpt-4.1-mini"),
    azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT"),
    api_key=os.getenv("AZURE_OPENAI_API_KEY"),
    api_version=os.getenv("AZURE_OPENAI_API_VERSION", "2024-02-15-preview"),
    temperature=0.4,
)

extraction_llm = AzureChatOpenAI(
    azure_deployment=os.getenv("AZURE_OPENAI_DEPLOYMENT", "gpt-4.1-mini"),
    azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT"),
    api_key=os.getenv("AZURE_OPENAI_API_KEY"),
    api_version=os.getenv("AZURE_OPENAI_API_VERSION", "2024-02-15-preview"),
    temperature=0,
)

# ---------------------------------------------------------------------------
# System prompts
# ---------------------------------------------------------------------------

# Base consultant prompt — the {prefill_block} placeholder is replaced at
# session-creation time with either the RAG pre-fill summary or a note
# saying no annual report was provided.
CONSULTANT_SYSTEM_PROMPT = """
You are a professional web consultant specializing in building websites for nonprofit organizations.
Your job is to gather ALL the information a developer needs to build a website from scratch — 
treat this conversation like a real client discovery session.

{prefill_block}

Guide the conversation naturally through these phases IN ORDER, but SKIP any fields
that are already marked as pre-filled above. Do not rush — be thorough in each phase
before moving on:

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PHASE 1 — Organization Overview
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
- Full legal name of the organization
- Mission statement (in their own words)
- Primary target audience (donors, volunteers, beneficiaries, general public, etc.)
- Overall tone/personality (professional, warm, urgent, inspiring, etc.)
- Key goals of the website (raise donations, recruit volunteers, inform, etc.)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PHASE 2 — Pages Needed
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Walk through which pages they want. Common nonprofit pages include:
Home, About Us, Our Team, Programs/Services, Impact/Stories,
Donate, Events, Volunteer, Blog/News, Contact, FAQ, Privacy Policy

For each page they confirm:
- What is the purpose of this page?
- Who is the primary audience visiting this page?

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PHASE 3 — Page Content (go page by page)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
For EACH confirmed page, gather:
- Main headline / tagline
- Body copy / text content (ask them to provide it or describe it)
- Call-to-action (button text + where it links)
- Images or media needed (do they have photos? Need stock? Video?)
- Any specific sections or components (stats block, testimonials, team grid, etc.)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PHASE 4 — Functionality & Features
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
- Online donation form (one-time and/or recurring?)
- Volunteer sign-up form
- Event calendar
- Newsletter / email list signup
- Blog / news section with comments?
- Member login / portal?
- Multi-language support?
- Accessibility requirements (ADA compliance)?
- Contact forms — what fields?

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PHASE 5 — Design Preferences
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
- Do they have an existing logo? Brand colors?
- Preferred color palette or feelings (warm, bold, calm, earthy, etc.)
- Font preferences (modern, traditional, playful, etc.)
- Any websites they like the look/feel of?
- Any design styles to avoid?
- Mobile-first requirements?

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PHASE 6 — Technical Requirements
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
- Do they have a domain name already?
- Current hosting setup (or starting fresh)?
- Preferred CMS (WordPress, Webflow, Squarespace, custom, etc.)
- Any third-party integrations needed (Salesforce, Mailchimp, PayPal, Stripe, etc.)
- Who will maintain the site after launch (staff, volunteer, agency)?
- Budget range (optional but helpful)?
- Timeline / launch deadline?

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
CONVERSATION RULES:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
- STEP 0 (only when a report was provided): Your opening message already showed the user
  a summary of pre-filled data and asked them to confirm or correct it. Wait for their
  response to that before asking any new questions. If they correct something, acknowledge
  the correction, update your understanding, and THEN move on to the missing fields.
- Ask ONE focused question at a time. Never dump multiple questions at once.
- Only ask about fields listed under "STILL NEEDS TO BE GATHERED FROM USER" above.
  Never re-ask about fields that are already pre-filled unless the user corrects them.
- If an answer is vague, probe deeper: "Can you tell me more about..." or "Do you have any existing content for that?"
- Offer helpful examples when they seem unsure (e.g., "Many nonprofits include a stats block on the homepage — something like '500 meals served daily'. Would that be useful?")
- Periodically summarize what you've gathered: "Great! So far I have: [summary]. Let's move on to..."
- Be warm, encouraging, and professional — they may not be tech-savvy.
- If they go off-topic, gently steer back.
- When all phases are complete, say: "I think I have everything I need! Type 'generate summary' and I'll put together a complete website brief for your developer."

Current date: {current_date}
""".strip()

# Default block used when no annual report is provided.
_NO_REPORT_BLOCK = (
    "No annual report was provided. Gather all information from the user "
    "through conversation, covering all phases below."
)

EXTRACTION_SYSTEM_PROMPT = """
You are a data extraction assistant. You will be given a full conversation transcript
between a web consultant and a nonprofit organization, and optionally a JSON object
of fields already pre-filled from the organization's annual report.

Extract all gathered website requirements into the following JSON schema.
If a field was not discussed, use null. Merge pre-filled data with anything
additional gathered during the conversation — conversation data takes precedence
if it contradicts the pre-filled data.

Respond ONLY with valid JSON, no markdown, no explanation.

Schema:
{{
  "organization": {{
    "name": "",
    "mission": "",
    "target_audience": "",
    "tone": "",
    "website_goals": []
  }},
  "pages": [
    {{
      "name": "",
      "purpose": "",
      "audience": "",
      "headline": "",
      "body_content": "",
      "cta_text": "",
      "cta_link_destination": "",
      "media_needed": "",
      "special_sections": []
    }}
  ],
  "features": {{
    "donation_form": null,
    "recurring_donations": null,
    "volunteer_signup": null,
    "event_calendar": null,
    "newsletter_signup": null,
    "blog": null,
    "member_portal": null,
    "multilanguage": null,
    "ada_compliance": null,
    "contact_form_fields": [],
    "other": []
  }},
  "design": {{
    "has_existing_logo": null,
    "brand_colors": [],
    "color_preferences": "",
    "font_preferences": "",
    "inspiration_sites": [],
    "styles_to_avoid": "",
    "mobile_first": null
  }},
  "technical": {{
    "has_domain": null,
    "domain_name": "",
    "hosting_situation": "",
    "preferred_cms": "",
    "integrations": [],
    "site_maintainer": "",
    "budget": "",
    "timeline": ""
  }},
  "notes": ""
}}
"""

# ---------------------------------------------------------------------------
# In-memory session store
# ---------------------------------------------------------------------------

_session_store: dict[str, ChatMessageHistory] = {}
_session_metadata: dict[str, dict] = {}
# Stores the pre-filled requirements dict (from RAG) per session, if any.
_session_prefilled: dict[str, dict] = {}
# Stores the per-session prompt (may differ because of injected prefill block).
_session_chains: dict[str, RunnableWithMessageHistory] = {}


def get_session_history(session_id: str) -> ChatMessageHistory:
    if session_id not in _session_store:
        _session_store[session_id] = ChatMessageHistory()
        _session_metadata[session_id] = {
            "created_at": datetime.utcnow().isoformat(),
            "last_active": datetime.utcnow().isoformat(),
            "message_count": 0,
        }
    return _session_store[session_id]


def session_exists(session_id: str) -> bool:
    return session_id in _session_store


def get_metadata(session_id: str) -> dict:
    return _session_metadata.get(session_id, {})


def increment_message_count(session_id: str) -> int:
    if session_id in _session_metadata:
        _session_metadata[session_id]["message_count"] += 1
        _session_metadata[session_id]["last_active"] = datetime.utcnow().isoformat()
    return _session_metadata.get(session_id, {}).get("message_count", 0)


def delete_session(session_id: str) -> None:
    _session_store.pop(session_id, None)
    _session_metadata.pop(session_id, None)
    _session_prefilled.pop(session_id, None)
    _session_chains.pop(session_id, None)


def list_all_sessions() -> list[dict]:
    return [{"session_id": sid, **meta} for sid, meta in _session_metadata.items()]


# ---------------------------------------------------------------------------
# Chain builder — one chain per session so the system prompt can vary
# ---------------------------------------------------------------------------

def _build_chain(prefill_block: str) -> RunnableWithMessageHistory:
    """Create a consultant chain with the given prefill block baked in."""
    resolved_prompt = CONSULTANT_SYSTEM_PROMPT.replace(
        "{prefill_block}", prefill_block
    ).replace(
        "{current_date}", datetime.utcnow().strftime("%B %d, %Y")
    )

    prompt = ChatPromptTemplate.from_messages([
        SystemMessage(content=resolved_prompt),
        MessagesPlaceholder(variable_name="history"),
        ("human", "{input}"),
    ])

    return RunnableWithMessageHistory(
        prompt | llm,
        get_session_history,
        input_messages_key="input",
        history_messages_key="history",
    )


# ---------------------------------------------------------------------------
# Public functions
# ---------------------------------------------------------------------------

def create_session(
    prefill_context: str | None = None,
    prefilled_data: dict | None = None,
) -> dict:
    """
    Create a new consultant session.

    Parameters
    ----------
    prefill_context : str, optional
        The formatted context block returned by
        ``rag_extractor.build_prefill_context_block()``.
        If provided, the consultant will know what's already been extracted
        and focus only on the remaining gaps.
    prefilled_data : dict, optional
        The raw pre-filled requirements dict (``rag_result["prefilled"]``).
        Stored so that ``extract_requirements`` can merge it with conversation
        data to produce the final brief.

    Returns
    -------
    { "session_id": str, "greeting": str }
    """
    session_id = str(uuid.uuid4())

    # Choose the prefill block to inject
    block = prefill_context if prefill_context else _NO_REPORT_BLOCK

    # Build and store a per-session chain
    chain = _build_chain(block)
    _session_chains[session_id] = chain

    # Store pre-filled data for later merging
    if prefilled_data:
        _session_prefilled[session_id] = prefilled_data

    # Build the greeting.
    # When a report was provided: show a formatted summary of what was found,
    # invite corrections, then flag the remaining gaps before asking anything.
    # When no report: plain intro asking for the org name.
    if prefill_context and prefilled_data:
        greet_system = f"""
You are a warm, professional web consultant who has just pre-read a nonprofit's annual report.
The user has connected for the first time.

Your ONLY job right now is to produce the opening message. Structure it EXACTLY like this:

1. One-sentence warm intro (e.g. "Hi there! I've had a chance to review your annual report ahead of our session.")

2. A clearly formatted summary block starting with:
   "Here's what I already know about your organization:"
   Then list EVERY pre-filled field as a bullet point in plain language, like:
     • Organization name: <value>
     • Mission: <value>
     • Target audience: <value>
     • Brand colors: <value>
     ... etc. for ALL found fields

3. An invitation to correct anything:
   "Please look this over — if anything is inaccurate or needs updating, just let me know and I'll make a note!"

4. A short note about what's still needed, listing the missing fields by their plain names in a natural sentence or two.
   e.g. "There are still a few gaps I need to fill in, like your preferred CMS, hosting setup, and font preferences."

5. A single closing line asking them to confirm the summary looks right before you move on.

Do NOT ask any discovery questions yet. Do NOT start gathering info. Just present the summary.

PRE-FILLED DATA:
PREFILLED_PLACEHOLDER

PRE-FILL CONTEXT (found vs missing keys):
CONTEXT_PLACEHOLDER
""".strip()

        # Substitute values directly — can't use f-string interpolation here
        # because the JSON contains { } that LangChain would try to parse as
        # template variables. Escape them by doubling, then inject.
        safe_json = json.dumps(prefilled_data, indent=2).replace("{", "{{").replace("}", "}}")
        safe_ctx  = prefill_context.replace("{", "{{").replace("}", "}}")
        greet_system = greet_system.replace("PREFILLED_PLACEHOLDER", safe_json)
        greet_system = greet_system.replace("CONTEXT_PLACEHOLDER",   safe_ctx)

        greet_prompt = ChatPromptTemplate.from_messages([
            ("system", greet_system),
            ("human", "Hello"),
        ])
        greeting_text = (greet_prompt | llm).invoke({}).content

    else:
        # No annual report — plain intro
        greet_system = (
            "The user has just connected. Greet them warmly as a web consultant, "
            "introduce yourself briefly, explain that you'll be gathering everything "
            "needed to build their nonprofit website, and ask for the organization's "
            "name to get started. Keep it to 3-4 sentences max."
        )
        greet_prompt = ChatPromptTemplate.from_messages([
            ("system", greet_system),
            ("human", "Hello"),
        ])
        greeting_text = (greet_prompt | llm).invoke({}).content

    history = get_session_history(session_id)
    history.add_ai_message(greeting_text)
    _session_metadata[session_id]["message_count"] = 1

    return {"session_id": session_id, "greeting": greeting_text}


def send_message(session_id: str, message: str) -> dict:
    """
    Pass a user message through the consultant chain and return:
      { "session_id": str, "reply": str, "message_count": int }
    """
    chain = _session_chains.get(session_id)
    if chain is None:
        # Fallback: rebuild a plain chain (shouldn't normally happen)
        chain = _build_chain(_NO_REPORT_BLOCK)
        _session_chains[session_id] = chain

    result = chain.invoke(
        {"input": message},
        config={"configurable": {"session_id": session_id}},
    )
    count = increment_message_count(session_id)

    return {
        "session_id": session_id,
        "reply": result.content,
        "message_count": count,
    }


def get_transcript(session_id: str) -> list[dict]:
    history = get_session_history(session_id)
    return [
        {
            "role": "assistant" if msg.type == "ai" else "user",
            "content": msg.content,
        }
        for msg in history.messages
    ]


def extract_requirements(session_id: str) -> dict:
    """
    Run the extraction LLM over the full conversation, merging with any
    pre-filled data from the annual report RAG pass.
    """
    history = get_session_history(session_id)

    if not history.messages:
        raise ValueError("No conversation history found for this session.")

    transcript = "\n".join(
        f"{'Consultant' if msg.type == 'ai' else 'Client'}: {msg.content}"
        for msg in history.messages
    )

    prefilled = _session_prefilled.get(session_id, {})
    prefilled_block = (
        f"\n\nPRE-FILLED FROM ANNUAL REPORT (merge these in):\n"
        f"{json.dumps(prefilled, indent=2)}\n"
        if prefilled else ""
    )

    extraction_prompt = ChatPromptTemplate.from_messages([
        ("system", EXTRACTION_SYSTEM_PROMPT),
        (
            "human",
            "Here is the conversation transcript:\n\n{transcript}\n"
            "{prefilled_block}\n"
            "Extract the requirements now.",
        ),
    ])

    raw = (extraction_prompt | extraction_llm).invoke(
        {"transcript": transcript, "prefilled_block": prefilled_block}
    ).content.strip()

    if raw.startswith("```"):
        raw = raw.split("```")[1]
        if raw.startswith("json"):
            raw = raw[4:]

    return json.loads(raw)